name: check manifest
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  check-manifest:
    name: Check manifest
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Check manifest'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry~=1.4.0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --with dev --verbose
      - name: Check manifest
        run: poetry run ./scripts/check-manifest.sh
